name: my_pixels
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  image_picker: ^0.6.3+1

dev_dependencies:
  meta: ^1.1.8
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
